spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/metapro
    username: postgres
    password: caragiale17


  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: metapro@gmail.com
    password: parola
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    user:
      name: admin
      password: admin
    basic:
      enabled: false
